# Config file for automatic testing at travis-ci.org

sudo: false
language: python
python: 3.5
env:
    - TOX_ENV=py27
    - TOX_ENV=py35
    - TOX_ENV=flake8

script: tox -e $TOX_ENV

install:
    - pip install tox
